### ISSUE TITLE
Expose MLAT-server's client.json

### ISSUE THREAD

**Issue by 0ip** [adsblol/infra#1]
Expose MLAT-server's client.json so that it can be consumed within adsblol/api similar to the JSON files of readsb as in https://github.com/adsblol/api/blob/main/app.py#L19.

**Comment by iakat** [comment]
I see what you mean now, I thought you wanted it publicly. This can/will be done. If you would like to contribute it, you can take a look at bases/readsb/base/readsb.yaml which mentions an nginx pod in the Deployment, serving files off of /run/readsb.

You would want to copy the relevant parts over to the mlat server

Sent from my phone

**Comment by 0ip** [comment]
Yeah I know some of these words 😄 

Really, I'm sorry, I have no experience with this at all. Will contribute to api once this is done.

**Comment by 0ip** [comment]
Merci!
