### ISSUE TITLE
CRDs missing

### ISSUE THREAD

**Issue by nickapos** [adsblol/infra#13]
Hello, when i do  kubectl apply -k manifests/default/ to deploy everything i get several messages about missing CRDs e.g
`esource mapping not found for name: "mlat-server-sync-map" namespace: "adsblol" from "manifests/default/": no matches for kind "ImageRepository" in version "image.toolkit.fluxcd.io/v1alpha2"
ensure CRDs are installed first
resource mapping not found for name: "api" namespace: "adsblol" from "manifests/default/": no matches for kind "ImageUpdateAutomation" in version "image.toolkit.fluxcd.io/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "history" namespace: "adsblol" from "manifests/default/": no matches for kind "ImageUpdateAutomation" in version "image.toolkit.fluxcd.io/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "mlat-server-sync-map" namespace: "adsblol" from "manifests/default/": no matches for kind "ImageUpdateAutomation" in version "image.toolkit.fluxcd.io/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "infra" namespace: "adsblol" from "manifests/default/": no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1beta2"
ensure CRDs are installed first
resource mapping not found for name: "api" namespace: "adsblol" from "manifests/default/": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first
resource mapping not found for name: "external-readsb" namespace: "adsblol" from "manifests/default/": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first
resource mapping not found for name: "hub-readsb" namespace: "adsblol" from "manifests/default/": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first
resource mapping not found for name: "ingest-readsb" namespace: "adsblol" from "manifests/default/": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first
resource mapping not found for name: "planes-readsb" namespace: "adsblol" from "manifests/default/": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
`
Is there  a way to deploy all the missing CRDs before the kubectl apply command?
Thank you very much

**Comment by iakat** [comment]
Installing flux and monitoring is left as an exercise for the user.

You can also avoid applying these manifests. The services will still run.
