### ISSUE TITLE
history and planes-readsb pods failing to start

### ISSUE THREAD

**Issue by nickapos** [adsblol/infra#14]
I am trying to run everything in minikube and everything works except these two pods.
For planes-readsb i see the following in the describe command in the test section:
` Liveness:   http-get http://:http/data/receiver.json delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  tcp-socket :30004 delay=15s timeout=1s period=10s #success=1 #failure=3
    Startup:    tcp-socket :30004 delay=15s timeout=1s period=10s #success=1 #failure=3
`
The Liveness test looks wrong to me. 
I am also getting the following events:
` Warning  FailedMount  55m (x20 over 4h39m)  kubelet  Unable to attach or mount volumes: unmounted volumes=[config-data], unattached volumes=[serve-run-http-config run adsblol state tar1090-config kube-api-access-kbnfr config-data]: timed out waiting for the condition
  Warning  FailedMount  35m (x19 over 5h7m)   kubelet  Unable to attach or mount volumes: unmounted volumes=[config-data], unattached volumes=[state tar1090-config kube-api-access-kbnfr config-data serve-run-http-config run adsblol]: timed out waiting for the condition
  Warning  FailedMount  10m (x17 over 4h44m)  kubelet  Unable to attach or mount volumes: unmounted volumes=[config-data], unattached volumes=[tar1090-config kube-api-access-kbnfr config-data serve-run-http-config run adsblol state]: timed out waiting for the condition
  Warning  FailedMount  6m8s (x23 over 5h9m)  kubelet  Unable to attach or mount volumes: unmounted volumes=[config-data], unattached volumes=[config-data serve-run-http-config run adsblol state tar1090-config kube-api-access-kbnfr]: timed out waiting for the condition
  Warning  FailedMount  1s (x161 over 5h11m)  kubelet  MountVolume.SetUp failed for volume "config-data" : secret "adsblol-rclone" not found
`

For history pod i get the following events:
` Warning  FailedMount  36m (x16 over 5h2m)     kubelet  Unable to attach or mount volumes: unmounted volumes=[rclone-config], unattached volumes=[rclone-emptydir kube-api-access-ntxkh adsblol-history nginx-conf remote-mount rclone-config]: timed out waiting for the condition
  Warning  FailedMount  27m (x20 over 5h4m)     kubelet  Unable to attach or mount volumes: unmounted volumes=[rclone-config], unattached volumes=[adsblol-history nginx-conf remote-mount rclone-config rclone-emptydir kube-api-access-ntxkh]: timed out waiting for the condition
  Warning  FailedMount  23m (x22 over 4h59m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[rclone-config], unattached volumes=[remote-mount rclone-config rclone-emptydir kube-api-access-ntxkh adsblol-history nginx-conf]: timed out waiting for the condition
  Warning  FailedMount  8m (x158 over 5h13m)    kubelet  MountVolume.SetUp failed for volume "rclone-config" : secret "adsblol-rclone" not found
  Warning  FailedMount  2m36s (x21 over 4h43m)  kubelet  Unable to attach or mount volumes: unmounted volumes=[rclone-config], unattached volumes=[nginx-conf remote-mount rclone-config rclone-emptydir kube-api-access-ntxkh adsblol-history]: timed out waiting for the condition`

Any advise on how to resolve these issues?
Thank you very much

**Comment by iakat** [comment]
I advise you understand the storage model of each component and patch accordingly to your needs.

This repository is currently a snapshot of the current state of the cluster, to base your work on.

Please consider contributing documentation / better defaults to the repository.
